version: 0.0
os: linux
files:
  - source: /
    destination: /emotive-chat-server/
hooks:
  ApplicationStart:
    - location: start-script
      timeout: 300
      runas: root
  AplicationStop:
    - location: stop-script
      timeout: 300
      runas: root
