version: 0.0
os: linux
files:
  - source: /
    destination: /app/
hooks:
  BeforeInstall:
    - location: /scripts/install-script
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/start-script
      timeout: 300
      runas: root
  AplicationStop:
    - location: /scripts/stop-script
      timeout: 300
      runas: root
